/* Syllabus content, kept separate from the graph so the node list stays readable.
   detail = what the topic is, covers = the subtopics, check = a self-test. */
const DETAILS = {
  "binary": { detail:"Everything a machine stores is a number in base two; the leaks in that abstraction cause a surprising share of real bugs.",
    covers:["Binary and hex, place value, bitwise operators", "Two's complement and integer overflow", "Floating point, and why 0.1 + 0.2 misbehaves", "Character encodings from ASCII to UTF-8"],
    check:"You can explain why a 32-bit signed integer stops near 2.1 billion." },
  "variables": { detail:"Names bound to values, and the type rules that decide which operations are legal on them.",
    covers:["Primitive versus reference types", "Scope, shadowing and lifetime", "Mutability and assignment semantics", "Static versus dynamic typing, and inference"],
    check:"You can predict whether changing one variable changes another." },
  "control": { detail:"Branching and looping, plus the habits that keep deeply conditional code readable.",
    covers:["Conditionals and boolean algebra", "Loops, break, continue and loop invariants", "Short-circuit evaluation", "Flattening nested branches into guard clauses"],
    check:"You can rewrite a three-deep nested conditional as flat guards without changing behaviour." },
  "functions": { detail:"The first real abstraction: a named, reusable unit of behaviour with a contract at its edges.",
    covers:["Parameters, return values and side effects", "The call stack and stack frames", "Closures and captured state", "Pure functions and referential transparency"],
    check:"You can describe what exists on the stack partway through a nested call." },
  "strings": { detail:"Text is deceptively hard: it is a sequence of bytes, of code points, and of things humans call characters, and those three disagree.",
    covers:["Immutability, and why concatenating in a loop is slow", "Slicing, splitting, joining, formatting", "Code points versus grapheme clusters", "Normalisation and comparison"],
    check:"You can explain why reversing a UTF-8 string byte by byte corrupts it." },
  "arrays": { detail:"A contiguous block of memory with constant-time indexing \u2014 the structure most others are built on top of.",
    covers:["Contiguous storage and O(1) access", "Dynamic arrays and amortised growth", "Row-major order and multi-dimensional layout", "Cache locality and why it dominates in practice"],
    check:"You can explain why appending is usually O(1) but occasionally O(n)." },
  "pointers": { detail:"Values that hold a location rather than data. Every linked structure and every aliasing bug lives here.",
    covers:["Addresses, dereferencing, null", "Stack versus heap allocation", "Shallow versus deep copies", "Aliasing, ownership and dangling references"],
    check:"You can draw a box-and-arrow diagram of two names sharing one object." },
  "recursion": { detail:"A function defined in terms of smaller versions of itself, and the stack that makes it work.",
    covers:["Base case and recursive case", "Stack growth and stack overflow", "Tail calls and tail-call elimination", "Converting recursion to explicit iteration"],
    check:"You can write a recursive routine and then rewrite it iteratively by hand." },
  "oop": { detail:"Bundling state with the behaviour that guards it, then modelling how those bundles relate.",
    covers:["Encapsulation and class invariants", "Composition over inheritance", "Polymorphism and interface design", "SOLID, and where it stops helping"],
    check:"You can justify why a piece of state belongs on one class and not another." },
  "functional": { detail:"Programs assembled from pure functions and values that never change, with effects pushed to the edges.",
    covers:["Purity and immutability", "map, filter, fold and their laws", "Higher-order functions and partial application", "Isolating side effects at the boundary"],
    check:"You can rewrite a stateful loop as a pipeline of transformations." },
  "modules": { detail:"Splitting a system into parts that hide their internals behind a contract, so it stays changeable.",
    covers:["Public interface versus private implementation", "Coupling, cohesion and dependency direction", "Layering and dependency inversion", "Semantic versioning and breaking changes"],
    check:"You can rewrite a module's internals without touching a single caller." },
  "testing": { detail:"Establishing that the code does what you claim, and finding out quickly when it stops.",
    covers:["Unit, integration and end-to-end levels", "Arrange-act-assert, naming, test design", "Mocks, stubs, fakes and their costs", "Reading stack traces, bisecting, minimal reproductions"],
    check:"You can turn a vague bug report into a failing test before fixing anything." },
  "complexity": { detail:"Describing how cost grows with input size, so you can compare approaches before writing either.",
    covers:["Big-O, big-theta, worst versus average case", "Amortised analysis", "Space complexity and time/space trade-offs", "Recurrences and the master theorem"],
    check:"You can state the complexity of a nested loop by reading it." },
  "linked": { detail:"Nodes chained by references: cheap insertion anywhere, no random access, poor cache behaviour.",
    covers:["Singly, doubly and circular variants", "O(1) insertion and deletion given a node", "Two-pointer technique and cycle detection", "Why traversal is slower than an array's"],
    check:"You can reverse a linked list in place without losing the tail." },
  "stackqueue": { detail:"Two restricted access patterns that turn out to drive traversal, scheduling and undo everywhere.",
    covers:["LIFO and FIFO semantics", "Array-backed versus node-backed implementations", "Deques and circular buffers", "Priority queues and their backing heap"],
    check:"You can build a queue from two stacks and state the amortised cost." },
  "hash": { detail:"Turning a key into an index, which buys average constant-time lookup at the cost of ordering.",
    covers:["Hash functions and uniform distribution", "Chaining versus open addressing", "Load factor, resizing and rehashing", "Adversarial inputs and degradation to O(n)"],
    check:"You can explain both why lookup is fast and when it stops being fast." },
  "trees": { detail:"Hierarchies with exactly one path between any two nodes \u2014 the shape behind search, parsing and indexing.",
    covers:["Binary search trees and traversal orders", "Balancing: AVL and red-black", "Tries and prefix search", "B-trees, and why databases prefer them"],
    check:"You can write in-order traversal both recursively and with an explicit stack." },
  "heaps": { detail:"A partially ordered tree that gives up full sorting in exchange for a fast minimum or maximum.",
    covers:["The heap property and array representation", "sift-up, sift-down, heapify", "Priority queue operations and costs", "Heapsort and streaming top-k"],
    check:"You can keep the k largest items from a stream without sorting it." },
  "graphsds": { detail:"Nodes and edges: the most general structure here, and the one this map itself is built from.",
    covers:["Adjacency lists versus matrices", "Directed, weighted, cyclic and bipartite variants", "Degree, paths, components", "Choosing a representation by density"],
    check:"You can pick a representation given node and edge counts and justify it." },
  "sorting": { detail:"Ordering data, and the standard arena for comparing algorithms honestly.",
    covers:["Insertion, merge, quick and their trade-offs", "Stability and in-place operation", "The O(n log n) comparison lower bound", "Counting and radix sort for restricted keys"],
    check:"You can name the sort your standard library uses and explain the choice." },
  "searching": { detail:"Halving a search space each step \u2014 the first genuinely logarithmic idea most people meet, and the easiest to write wrong.",
    covers:["The loop invariant and off-by-one errors", "lower_bound and upper_bound variants", "Binary search on the answer", "Searching rotated and implicit spaces"],
    check:"You can write binary search correctly from scratch, boundaries included." },
  "divide": { detail:"Split the problem, solve the parts, combine the results \u2014 and account honestly for the combining.",
    covers:["Split, solve, combine as a pattern", "Recurrences and the master theorem", "Merge sort, quickselect, closest pair", "When combination cost defeats the split"],
    check:"You can derive a running time from its recurrence." },
  "greedy": { detail:"Take the locally best option, and know precisely when that yields a global optimum.",
    covers:["The greedy choice property", "Exchange argument proofs", "Interval scheduling, Huffman coding", "Where greedy fails and DP takes over"],
    check:"You can either prove a greedy choice safe or produce the counterexample." },
  "backtrack": { detail:"Systematic search through a space of choices, undoing the ones that lead nowhere.",
    covers:["State space trees and pruning", "Constraint propagation", "N-queens, sudoku, subset and permutation generation", "The cost of exhaustive search"],
    check:"You can add pruning to a brute-force search and measure what it saved." },
  "dp": { detail:"Solving overlapping subproblems once and reusing the answers \u2014 the technique people find hardest and use most.",
    covers:["Overlapping subproblems and optimal substructure", "Memoisation versus bottom-up tables", "Designing the state and the transition", "Rolling arrays and space reduction"],
    check:"You can state the subproblem and transition before writing any code." },
  "graphalgo": { detail:"Traversal, shortest paths, spanning trees and connectivity over networks of nodes.",
    covers:["BFS, DFS, topological sort", "Dijkstra, Bellman-Ford, A*", "Minimum spanning trees", "Union-find and dynamic connectivity"],
    check:"You can choose a shortest-path algorithm given weights, negatives and cycles." },
  "stringalgo": { detail:"Where text meets algorithms: matching, aligning and splitting sequences efficiently.",
    covers:["Naive matching versus KMP and Rabin-Karp", "Edit distance and sequence alignment", "Suffix arrays and suffix trees", "Tokenisation and normalisation"],
    check:"You can fill in an edit-distance grid by hand for two short words." },
  "discrete": { detail:"Logic, sets, counting and proof \u2014 the grammar the rest of computer science is written in.",
    covers:["Propositional and predicate logic", "Sets, relations, functions, equivalence", "Induction and proof by contradiction", "Combinatorics, pigeonhole, basic graph theory"],
    check:"You can prove a loop invariant by induction." },
  "linalg": { detail:"Vectors, matrices and the transformations between them. Nearly every model further along this map is matrix multiplication underneath.",
    covers:["Vectors, matrices, matrix multiplication", "Rank, span, basis, linear independence", "Eigenvalues, eigenvectors, SVD", "Projections and change of basis"],
    check:"You can predict the output shape of a chain of matrix products." },
  "prob": { detail:"Reasoning about uncertainty: distributions, expectation, and how evidence updates belief.",
    covers:["Sample spaces, conditional probability, Bayes", "Random variables and standard distributions", "Expectation, variance, covariance", "Independence and the central limit theorem"],
    check:"You can compute a posterior from a prior and a likelihood." },
  "stats": { detail:"Drawing conclusions from samples, and quantifying how much to trust them.",
    covers:["Estimators, bias and variance", "Confidence intervals and hypothesis tests", "Maximum likelihood estimation", "Sampling bias, confounding, Simpson's paradox"],
    check:"You can say precisely what a p-value does and does not claim." },
  "calculus": { detail:"Rates of change. Derivatives are the mechanism by which a model learns which direction to move.",
    covers:["Derivatives, partial derivatives, gradients", "The chain rule, in depth", "Jacobians and Hessians", "Taylor approximation and local behaviour"],
    check:"You can differentiate a composed function by hand with the chain rule." },
  "optimization": { detail:"Finding the input that minimises a function, and knowing whether the answer you found is the real one.",
    covers:["Convexity, local versus global minima", "Constraints and Lagrange multipliers", "First and second order methods", "Step size, conditioning and convergence"],
    check:"You can tell whether a loss surface is convex and say why it matters." },
  "infotheory": { detail:"Measuring surprise. Most of the loss functions further down this map are entropy in disguise.",
    covers:["Entropy and self-information", "Cross-entropy and KL divergence", "Mutual information", "Compression bounds and coding"],
    check:"You can explain why cross-entropy is the natural loss for classification." },
  "memory": { detail:"What the machine is actually doing beneath your variables: allocation, lifetime and the cache.",
    covers:["Stack versus heap, allocation, fragmentation", "Manual freeing versus garbage collection", "Reference counting and cycles", "Cache lines, locality, false sharing"],
    check:"You can explain why traversing a matrix by rows beats by columns." },
  "os": { detail:"Processes, scheduling and the boundary between your program and the hardware.",
    covers:["Processes, threads, context switches", "Scheduling policies and fairness", "Virtual memory, paging, address spaces", "System calls and the kernel boundary"],
    check:"You can narrate what happens between a read() call and the bytes arriving." },
  "concurrency": { detail:"Doing several things at once without corrupting shared state or deadlocking.",
    covers:["Race conditions and critical sections", "Locks, semaphores, deadlock and livelock", "Async, event loops, futures and tasks", "Concurrency versus parallelism"],
    check:"You can spot a race condition while reading a diff." },
  "networking": { detail:"Moving bytes between machines reliably across a medium that is not reliable.",
    covers:["Layering and packet switching", "TCP versus UDP, handshakes, retransmission", "HTTP, TLS, DNS", "Latency versus bandwidth, backpressure"],
    check:"You can trace a request from typed URL to rendered page." },
  "databases": { detail:"Storing, indexing and querying data that outlives the process that wrote it.",
    covers:["Relational modelling and normalisation", "Indexes, query plans, join strategies", "Transactions, ACID, isolation levels", "Key-value, document and vector stores"],
    check:"You can read a query plan and explain why a query is slow." },
  "distributed": { detail:"Many machines behaving as one, where partial failure is the normal case rather than the exception.",
    covers:["Replication, sharding, consensus", "CAP and consistency models", "Failure detection, retries, idempotency", "Queues, event logs and exactly-once myths"],
    check:"You can reason through what happens when one node stops responding." },
  "gpu": { detail:"Thousands of cores running the same arithmetic at once \u2014 the hardware that made deep learning practical.",
    covers:["SIMD, warps, kernels and occupancy", "Memory hierarchy and transfer cost", "Batching and arithmetic intensity", "CUDA, tensor cores, kernel fusion at a high level"],
    check:"You can explain why larger batches often cost less per sample." },
  "datawrangle": { detail:"Loading, cleaning and shaping data before any model sees it \u2014 where most real project time actually goes.",
    covers:["Loading, joining and reshaping tabular data", "Missing values, outliers, duplicates", "Train, validation and test splits", "Leakage, scaling and categorical encoding"],
    check:"You can build a split that leaks nothing into training." },
  "supervised": { detail:"Learning a mapping from inputs to labels, starting with models you can still interpret.",
    covers:["Linear and logistic regression", "Trees, random forests, gradient boosting", "Loss functions and regularisation", "The bias-variance trade-off"],
    check:"You can beat a sensible baseline and explain what the model picked up on." },
  "unsupervised": { detail:"Finding structure with no labels to guide you, and judging whether the structure is real.",
    covers:["k-means and hierarchical clustering", "PCA and dimensionality reduction", "Density estimation", "Evaluating structure without ground truth"],
    check:"You can defend a choice of cluster count on more than a plot." },
  "evaluation": { detail:"Deciding whether a model is actually good, which is a harder problem than training one.",
    covers:["Cross-validation and holdout discipline", "Precision, recall, ROC and PR curves", "Overfitting, underfitting, learning curves", "Choosing a metric that matches the real goal"],
    check:"You can explain how 99% accuracy can be a worthless result." },
  "graddesc": { detail:"Following the slope of the loss downhill in small steps. The whole of training is this loop.",
    covers:["Gradients, learning rate and step size", "Batch, stochastic and mini-batch variants", "Momentum, RMSProp, Adam", "Diagnosing divergence, plateaus and oscillation"],
    check:"You can read a loss curve and say what to change next." },
  "nn": { detail:"Layers of weighted sums and nonlinearities stacked into a function flexible enough to fit almost anything.",
    covers:["Neurons, layers, weights and biases", "Activation functions and why nonlinearity matters", "Depth, width and universal approximation", "Initialisation, dropout, normalisation"],
    check:"You can write a forward pass using only matrix multiplications." },
  "backprop": { detail:"The chain rule applied backwards over a computation graph, producing every gradient in one pass.",
    covers:["The computation graph", "Forward and backward passes", "Vanishing and exploding gradients", "Automatic differentiation as frameworks implement it"],
    check:"You can derive the gradients of a two-layer network by hand." },
  "cnn": { detail:"Sharing weights across a grid, which is why these work on images and why they are cheap.",
    covers:["Convolution, kernels, stride, padding", "Pooling and receptive fields", "Translation invariance through weight sharing", "Residual connections and depth"],
    check:"You can compute the output shape of a convolutional stack on paper." },
  "rnn": { detail:"Carrying state across time steps, and running into the limits that motivated attention.",
    covers:["Hidden state and unrolling", "LSTM and GRU gating", "Backpropagation through time", "Why long-range dependencies degrade"],
    check:"You can explain what an LSTM gate is actually gating." },
  "embeddings": { detail:"Turning discrete things into vectors where geometric distance carries meaning.",
    covers:["One-hot versus dense representations", "Embedding tables and how they are learned", "Cosine similarity and vector search", "word2vec through to sentence embeddings"],
    check:"You can say what proximity in an embedding space does and does not imply." },
  "attention": { detail:"Letting every position consult every other position directly. This is the architecture behind current language models.",
    covers:["Query, key, value and scaled dot-product", "Multi-head attention", "Positional encoding schemes", "Encoder, decoder and decoder-only stacks"],
    check:"You can trace the tensor shapes through one attention block." },
  "rl": { detail:"Learning a policy from reward rather than from labelled answers.",
    covers:["States, actions, rewards, policies", "Markov decision processes and value functions", "Q-learning and policy gradients", "Exploration, exploitation and reward hacking"],
    check:"You can frame a real problem as an MDP and name its reward." },
  "scaletrain": { detail:"Splitting a model and its data across many GPUs without the run falling over.",
    covers:["Data, tensor and pipeline parallelism", "Mixed precision and gradient accumulation", "Checkpointing and fault tolerance", "Scaling laws and compute budgeting"],
    check:"You can estimate whether a given model fits in the memory you have." },
  "nlp": { detail:"Representing and processing human language, from splitting text into tokens upward.",
    covers:["Tokenisation, BPE, vocabulary design", "Language modelling objectives", "Classification, tagging, summarisation", "Perplexity, BLEU, and their limitations"],
    check:"You can explain what a tokeniser does to a word it has never seen." },
  "cv": { detail:"Detection, segmentation and recognition in images and video.",
    covers:["Classification, detection, segmentation", "Augmentation and dataset construction", "Transfer learning from pretrained backbones", "Vision transformers versus convolutional nets"],
    check:"You can fine-tune a pretrained backbone on a few thousand images." },
  "llm": { detail:"Transformers pretrained on enormous corpora to predict the next token, and everything that follows from that objective.",
    covers:["Pretraining objectives and corpus construction", "Context windows and KV caching", "Sampling: temperature, top-p, beam search", "Instruction tuning and RLHF in outline"],
    check:"You can explain why a model loops at low temperature." },
  "finetune": { detail:"Adapting a pretrained model to your task without paying to retrain the whole thing.",
    covers:["Full fine-tuning versus parameter-efficient methods", "LoRA and QLoRA: rank, adapters, merging", "Quantisation and memory budgeting", "Dataset construction and catastrophic forgetting"],
    check:"You can decide between prompting and fine-tuning with reasons, not vibes." },
  "rag": { detail:"Fetching relevant material at query time and placing it in the model's context.",
    covers:["Chunking and indexing strategies", "Vector search and hybrid retrieval", "Reranking and context assembly", "Grounding, citation and retrieval failure modes"],
    check:"You can diagnose why a retrieval system returned the wrong passage." },
  "agents": { detail:"Models that plan, call tools and act across multiple steps, with all the failure modes that implies.",
    covers:["Tool calling and structured output", "Planning loops and state management", "Memory and context budgeting", "Loops, cascading errors and guardrails"],
    check:"You can trace an agent run and locate the step where it went wrong." },
  "mlops": { detail:"Getting a model into production and keeping it working once it is there.",
    covers:["Packaging, serving, inference latency", "Versioning models, data and prompts", "Monitoring, drift detection, rollback", "Cost, batching and throughput"],
    check:"You can deploy a model and detect degradation before users report it." },
  "alignment": { detail:"Measuring what a model actually does and shaping it toward what people intended.",
    covers:["Benchmarks and what they fail to capture", "Red-teaming and adversarial evaluation", "RLHF, preference data, constitutional methods", "Interpretability, in outline"],
    check:"You can design an eval that would catch the specific failure you care about." },
  "relevance": { detail:"As AI absorbs more routine cognitive work, the durable human roles concentrate in verification, judgment and accountability \u2014 and those can be built deliberately rather than hoped for.",
    covers:["Comparative advantage versus absolute advantage", "Task exposure: routine/non-routine \u00d7 manual/cognitive", "The jagged frontier and the verification gap", "T-shaped skills, systems thinking and accountability"],
    check:"You can map your own week's tasks onto the exposure quadrant and justify each placement." },
};
